# Uzbekiston viloyatlari va tumanlari
# Hardcoded reference data

REGIONS = {
    "toshkent_sh": {
        "name": "Toshkent shahar",
        "districts": {
            "bektemir": "Bektemir",
            "chilonzor": "Chilonzor",
            "yashnobod": "Yashnobod",
            "mirobod": "Mirobod",
            "mirzo_ulugbek": "Mirzo Ulug'bek",
            "sergeli": "Sergeli",
            "shayxontohur": "Shayxontohur",
            "olmazor": "Olmazor",
            "uchtepa": "Uchtepa",
            "yakkasaroy": "Yakkasaroy",
            "yunusobod": "Yunusobod",
        },
    },
    "toshkent_v": {
        "name": "Toshkent viloyati",
        "districts": {
            "angren": "Angren",
            "olmaliq": "Olmaliq",
            "chirchiq": "Chirchiq",
            "bekobod": "Bekobod",
            "bo'ka": "Bo'ka",
            "bo'stonliq": "Bo'stonliq",
            "chinoz": "Chinoz",
            "qibray": "Qibray",
            "oqqo'rg'on": "Oqqo'rg'on",
            "ohangaron": "Ohangaron",
            "parkent": "Parkent",
            "piskent": "Piskent",
            "quyi_chirchiq": "Quyi Chirchiq",
            "o'rta_chirchiq": "O'rta Chirchiq",
            "yuqori_chirchiq": "Yuqori Chirchiq",
            "zangiota": "Zangiota",
            "toshkent_t": "Toshkent tumani",
        },
    },
    "andijon": {
        "name": "Andijon viloyati",
        "districts": {
            "andijon_sh": "Andijon shahar",
            "xonobod": "Xonobod",
            "asaka": "Asaka",
            "baliqchi": "Baliqchi",
            "bo'z": "Bo'z",
            "buloqboshi": "Buloqboshi",
            "izboskan": "Izboskan",
            "jalaquduq": "Jalaquduq",
            "marhamat": "Marhamat",
            "oltinko'l": "Oltinko'l",
            "paxtaobod": "Paxtaobod",
            "shahrixon": "Shahrixon",
            "ulug'nor": "Ulug'nor",
            "xo'jaobod": "Xo'jaobod",
            "qo'rg'ontepa": "Qo'rg'ontepa",
        },
    },
    "buxoro": {
        "name": "Buxoro viloyati",
        "districts": {
            "buxoro_sh": "Buxoro shahar",
            "kogon": "Kogon",
            "g'ijduvon": "G'ijduvon",
            "jondor": "Jondor",
            "kogon_t": "Kogon tumani",
            "olot": "Olot",
            "peshku": "Peshku",
            "qorako'l": "Qorako'l",
            "qorovulbozor": "Qorovulbozor",
            "romitan": "Romitan",
            "shofirkon": "Shofirkon",
            "vobkent": "Vobkent",
        },
    },
    "farg'ona": {
        "name": "Farg'ona viloyati",
        "districts": {
            "farg'ona_sh": "Farg'ona shahar",
            "qo'qon": "Qo'qon",
            "marg'ilon": "Marg'ilon",
            "quvasoy": "Quvasoy",
            "bag'dod": "Bag'dod",
            "beshariq": "Beshariq",
            "buvayda": "Buvayda",
            "dang'ara": "Dang'ara",
            "furqat": "Furqat",
            "oltiariq": "Oltiariq",
            "o'zbekiston": "O'zbekiston",
            "qo'shtepa": "Qo'shtepa",
            "rishton": "Rishton",
            "so'x": "So'x",
            "toshloq": "Toshloq",
            "uchko'prik": "Uchko'prik",
            "yozyovon": "Yozyovon",
        },
    },
    "jizzax": {
        "name": "Jizzax viloyati",
        "districts": {
            "jizzax_sh": "Jizzax shahar",
            "arnasoy": "Arnasoy",
            "baxmal": "Baxmal",
            "do'stlik": "Do'stlik",
            "forish": "Forish",
            "g'allaorol": "G'allaorol",
            "mirzacho'l": "Mirzacho'l",
            "paxtakor": "Paxtakor",
            "sharof_rashidov": "Sharof Rashidov",
            "yangiobod": "Yangiobod",
            "zafarobod": "Zafarobod",
            "zomin": "Zomin",
        },
    },
    "xorazm": {
        "name": "Xorazm viloyati",
        "districts": {
            "urganch_sh": "Urganch shahar",
            "xiva": "Xiva",
            "bog'ot": "Bog'ot",
            "gurlan": "Gurlan",
            "qo'shko'pir": "Qo'shko'pir",
            "shovot": "Shovot",
            "urganch_t": "Urganch tumani",
            "xazarasp": "Xazarasp",
            "xonqa": "Xonqa",
            "yangiariq": "Yangiariq",
            "yangibozor": "Yangibozor",
        },
    },
    "namangan": {
        "name": "Namangan viloyati",
        "districts": {
            "namangan_sh": "Namangan shahar",
            "chortoq": "Chortoq",
            "chust": "Chust",
            "kosonsoy": "Kosonsoy",
            "mingbuloq": "Mingbuloq",
            "namangan_t": "Namangan tumani",
            "norin": "Norin",
            "pop": "Pop",
            "to'raqo'rg'on": "To'raqo'rg'on",
            "uchqo'rg'on": "Uchqo'rg'on",
            "uychi": "Uychi",
            "yangiqo'rg'on": "Yangiqo'rg'on",
        },
    },
    "navoiy": {
        "name": "Navoiy viloyati",
        "districts": {
            "navoiy_sh": "Navoiy shahar",
            "zarafshon": "Zarafshon",
            "g'ozg'on": "G'ozg'on",
            "karmana": "Karmana",
            "konimex": "Konimex",
            "navbahor": "Navbahor",
            "nurota": "Nurota",
            "qiziltepa": "Qiziltepa",
            "tomdi": "Tomdi",
            "uchquduq": "Uchquduq",
            "xatirchi": "Xatirchi",
        },
    },
    "qashqadaryo": {
        "name": "Qashqadaryo viloyati",
        "districts": {
            "qarshi_sh": "Qarshi shahar",
            "shahrisabz": "Shahrisabz",
            "chiroqchi": "Chiroqchi",
            "dehqonobod": "Dehqonobod",
            "g'uzor": "G'uzor",
            "kasbi": "Kasbi",
            "kitob": "Kitob",
            "koson": "Koson",
            "mirishkor": "Mirishkor",
            "muborak": "Muborak",
            "nishon": "Nishon",
            "qamashi": "Qamashi",
            "yakkabog'": "Yakkabog'",
        },
    },
    "samarqand": {
        "name": "Samarqand viloyati",
        "districts": {
            "samarqand_sh": "Samarqand shahar",
            "kattaqo'rg'on": "Kattaqo'rg'on",
            "bulung'ur": "Bulung'ur",
            "ishtixon": "Ishtixon",
            "jomboy": "Jomboy",
            "loyish": "Loyish",
            "narpay": "Narpay",
            "nurobod": "Nurobod",
            "oqdaryo": "Oqdaryo",
            "pastdarg'om": "Pastdarg'om",
            "paxtachi": "Paxtachi",
            "payariq": "Payariq",
            "samarqand_t": "Samarqand tumani",
            "toyloq": "Toyloq",
            "urgut": "Urgut",
        },
    },
    "sirdaryo": {
        "name": "Sirdaryo viloyati",
        "districts": {
            "guliston_sh": "Guliston shahar",
            "yangiyer": "Yangiyer",
            "shirin": "Shirin",
            "boyovut": "Boyovut",
            "guliston_t": "Guliston tumani",
            "xovos": "Xovos",
            "mirzaobod": "Mirzaobod",
            "oqoltin": "Oqoltin",
            "sardoba": "Sardoba",
            "sayxunobod": "Sayxunobod",
        },
    },
    "surxondaryo": {
        "name": "Surxondaryo viloyati",
        "districts": {
            "termiz_sh": "Termiz shahar",
            "angor": "Angor",
            "bandixon": "Bandixon",
            "boysun": "Boysun",
            "denov": "Denov",
            "jarqo'rg'on": "Jarqo'rg'on",
            "muzrabot": "Muzrabot",
            "oltinsoy": "Oltinsoy",
            "qiziriq": "Qiziriq",
            "qumqo'rg'on": "Qumqo'rg'on",
            "sariosiyo": "Sariosiyo",
            "sherobod": "Sherobod",
            "sho'rchi": "Sho'rchi",
            "termiz_t": "Termiz tumani",
            "uzun": "Uzun",
        },
    },
    "qoraqalpog'iston": {
        "name": "Qoraqalpog'iston Respublikasi",
        "districts": {
            "nukus_sh": "Nukus shahar",
            "amudaryo": "Amudaryo",
            "beruniy": "Beruniy",
            "chimboy": "Chimboy",
            "ellikqala": "Ellikqala",
            "kegeyli": "Kegeyli",
            "mo'ynoq": "Mo'ynoq",
            "nukus_t": "Nukus tumani",
            "qanliko'l": "Qanliko'l",
            "qo'ng'irot": "Qo'ng'irot",
            "shumanay": "Shumanay",
            "taxtako'pir": "Taxtako'pir",
            "to'rtko'l": "To'rtko'l",
            "xo'jayli": "Xo'jayli",
        },
    },
}


def get_region_name(region_id: str) -> str:
    return REGIONS.get(region_id, {}).get("name", region_id)


def get_district_name(region_id: str, district_id: str) -> str:
    region = REGIONS.get(region_id, {})
    return region.get("districts", {}).get(district_id, district_id)


def get_full_location(region_id: str, district_id: str) -> str:
    return f"{get_district_name(region_id, district_id)}, {get_region_name(region_id)}"


def get_short_location(region_id: str, district_id: str) -> str:
    return get_district_name(region_id, district_id)
